# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Choose Site'
        required: true
        default: 'dev'
        type: choice
        options:
          - pro_elite
          - pro_premium
          - pre
          - dev
      solutions:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # environment: ${{ github.event.inputs.name }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      shell: pwsh
      run: |
        ${{ github.event.inputs.solutions }} | foreach-object { echo "---$_---"}
        
